clear; clc; close all;

%% CurvatureFeasibilityStudy.m
% Phase 3 Part B: vessel curvature demand analysis and CTR curvature
% capacity comparison.
%
% Geometry-only note:
% This script compares centerline curvature demand with the maximum
% curvature generated by the simplified PCC CTR model. It does not imply
% real insertion feasibility because contact, friction, tissue deformation,
% vessel wall collision, and clinical constraints are not modeled.

%% Parameter setting
centerlineFile = find_project_file({'*Centerline*curve*.fcsv', '*centerline*curve*.fcsv'});

numCenterlineSamples = 300;
smoothingWindow = 15;
maxCurvatureSearchMargin = 12;
showAnalyzeCenterlinePlots = false;

% Representative CTR sampling ranges. Rho is entered in mm, theta in deg.
rho1_vals = 0;                  % reference translation in current Robot.m
rho2_vals = 0:20:60;
rho3_vals = 0:20:80;
theta1_vals = -180:45:180;
theta2_vals = -180:45:180;
theta3_vals = -180:45:180;

resultsMatFile = 'CurvatureFeasibilityResults.mat';

%% CTR model initialization
[robot, ~] = initialize_ctr_model();

%% Main computation: analyze vessel centerline
% AnalyzeCenterline returns Slicer coordinates in mm, so its curvature is
% in 1/mm. Convert vessel curvature to 1/m before comparing with robot.kappa.
centerline = AnalyzeCenterline(centerlineFile, numCenterlineSamples, ...
    smoothingWindow, maxCurvatureSearchMargin, showAnalyzeCenterlinePlots);

P_vessel = centerline.P_smooth;             % mm
s_vessel = centerline.s_uniform;            % mm
kappa_vessel_1_per_mm = centerline.kappa;
kappa_vessel_1_per_m = 1000 * kappa_vessel_1_per_mm;

[kappa_vessel_max, idx_max] = max(kappa_vessel_1_per_m);
p_maxcurv = P_vessel(idx_max,:);

%% Main computation: scan CTR curvature capacity
nSamples = numel(rho1_vals) * numel(rho2_vals) * numel(rho3_vals) * ...
    numel(theta1_vals) * numel(theta2_vals) * numel(theta3_vals);

q_log = zeros(nSamples, 6);
max_link_curvature_1_per_m = zeros(nSamples, 1);

sampleIdx = 0;
for rho1 = rho1_vals
    for rho2 = rho2_vals
        for rho3 = rho3_vals
            for theta1 = theta1_vals
                for theta2 = theta2_vals
                    for theta3 = theta3_vals
                        sampleIdx = sampleIdx + 1;

                        q = [rho1, rho2, rho3, theta1, theta2, theta3];
                        robot.fkin(q);

                        q_log(sampleIdx,:) = q;
                        max_link_curvature_1_per_m(sampleIdx) = max(robot.kappa);
                    end
                end
            end
        end
    end
end

[kappa_CTR_max, idx_ctr_max] = max(max_link_curvature_1_per_m);
q_at_kappa_CTR_max = q_log(idx_ctr_max,:);
R_kappa = kappa_CTR_max / kappa_vessel_max;

if R_kappa > 1
    interpretation = "R_kappa > 1: simplified CTR may geometrically match the maximum vessel curvature demand.";
elseif R_kappa < 1
    interpretation = "R_kappa < 1: simplified CTR may be geometrically insufficient for the maximum vessel curvature demand.";
else
    interpretation = "R_kappa = 1: simplified CTR is exactly at the maximum vessel curvature demand in this scan.";
end

%% Visualization: 3D vessel centerline and maximum-curvature point
figure('Name','Phase 3 Part B - Vessel centerline');
plot3(P_vessel(:,1), P_vessel(:,2), P_vessel(:,3), ...
    'b-', 'LineWidth', 2);
hold on;
plot3(p_maxcurv(1), p_maxcurv(2), p_maxcurv(3), ...
    'ro', 'MarkerSize', 9, 'LineWidth', 2);
axis equal; grid on;
xlabel('X (mm)');
ylabel('Y (mm)');
zlabel('Z (mm)');
title('Vessel centerline with maximum-curvature point');
legend('Smoothed vessel centerline', 'Maximum-curvature point', 'Location', 'best');

%% Visualization: curvature versus arc length profile
figure('Name','Phase 3 Part B - Vessel curvature profile');
plot(s_vessel, kappa_vessel_1_per_m, 'LineWidth', 1.6);
hold on;
plot(s_vessel(idx_max), kappa_vessel_max, ...
    'ro', 'MarkerSize', 8, 'LineWidth', 2);
grid on;
xlabel('Arc length (mm)');
ylabel('Curvature (1/m)');
title('Vessel curvature demand along centerline');
legend('Vessel curvature', 'Maximum curvature', 'Location', 'best');

%% Summary output
summaryTable = table(kappa_vessel_max, kappa_CTR_max, R_kappa, ...
    q_at_kappa_CTR_max, interpretation, ...
    'VariableNames', {'kappa_vessel_max','kappa_CTR_max', ...
    'R_kappa','q_at_kappa_CTR_max','interpretation'});

curvatureResults = struct();
curvatureResults.centerlineFile = centerlineFile;
curvatureResults.centerline = centerline;
curvatureResults.kappa_vessel_profile_1_per_m = kappa_vessel_1_per_m;
curvatureResults.kappa_vessel_max_1_per_m = kappa_vessel_max;
curvatureResults.kappa_CTR_max_1_per_m = kappa_CTR_max;
curvatureResults.R_kappa = R_kappa;
curvatureResults.q_at_kappa_CTR_max = q_at_kappa_CTR_max;
curvatureResults.q_log = q_log;
curvatureResults.max_link_curvature_1_per_m = max_link_curvature_1_per_m;
curvatureResults.summaryTable = summaryTable;
save(resultsMatFile, 'curvatureResults');

fprintf('\nPhase 3 Part B curvature feasibility study complete.\n');
fprintf('Centerline file: %s\n', centerlineFile);
fprintf('Curvatures in the summary table are reported in 1/m.\n');
fprintf('Number of sampled CTR configurations: %d\n', nSamples);
fprintf('Saved results to %s\n\n', resultsMatFile);
disp('Summary table:');
disp(summaryTable);
disp('Important limitation: this is geometric feasibility only, not physical or clinical insertion feasibility.');

%% Local helper functions
function [robot, tubes] = initialize_ctr_model()
    % Same tube parameter set as Phase 2 / WorkspaceSamplingTemplate.m.
    tube1 = Tube(3.046e-3, 3.3e-3, 1/17,  90e-3, 50e-3, 1935e6);
    tube2 = Tube(2.386e-3, 2.64e-3, 1/22, 170e-3, 50e-3, 1935e6);
    tube3 = Tube(1.726e-3, 1.98e-3, 1/29, 250e-3, 50e-3, 1935e6);

    tubes = [tube1, tube2, tube3];
    robot = Robot(tubes, false);
end

function file = find_project_file(patterns)
    % Locate the Slicer centerline file without hard-coding spaces or suffixes.
    for i = 1:numel(patterns)
        hits = dir(patterns{i});
        hits = hits(~[hits.isdir]);
        if ~isempty(hits)
            [~, order] = max([hits.bytes]);
            file = hits(order).name;
            return;
        end
    end

    error('CurvatureFeasibilityStudy:MissingCenterline', ...
        'Could not find a vessel centerline .fcsv file.');
end
